version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: store   # Replace 'store' with your desired database name
      POSTGRES_USER: "user"  # Replace 'user' with your desired username
      POSTGRES_PASSWORD: password  # Replace 'password' with your desired password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local